=== robert0714/risDbdocCompareStandalone/src/main/java/com/iisigroup/config/model/Items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
  targetNamespace="http://xmlns.oracle.com/communications/inventory/webservice/IISI/items"
  elementFormDefault="qualified" 
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:items="http://xmlns.oracle.com/communications/inventory/webservice/IISI/items" xmlns:invcom="http://xmlns.oracle.com/communications/inventory/webservice/common">
  
    <complexType name="item">
    	<sequence>
    		<element name="key" type="string"></element>
    		<element name="value" type="string"></element>
    	</sequence>

    </complexType>

    <complexType name="itemList">
		<sequence>
			<element name="item" type="items:item" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="itemList" type="items:itemList" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="key" type="string"></attribute>
  </complexType>
  
  <complexType name="itemType">
		<sequence>
			<element name="dataType" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="item" type="items:item" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="itemList" type="items:itemList" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
  </complexType>
  <element name="config" type="items:itemType"></element>
</schema>

=== robert0714/risDbdocCompareStandalone/src/main/java/com/iisigroup/config/model/ItemsSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<items:config
	xmlns:items="http://xmlns.oracle.com/communications/inventory/webservice/IISI/items"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.oracle.com/communications/inventory/webservice/IISI/items Items.xsd ">
	<items:dataType>Robert Toolkits</items:dataType>
	<items:itemList key="RL_REG_DATA_BATCH">
		<items:itemList key="RLDF0W100">
			<items:item>
				<items:key>CHINESE_NAME</items:key>
				<items:value>無戶籍者結離婚登記</items:value>
			</items:item>
			<items:item>
				<items:key>SYMBOL_CODE</items:key>
				<items:value>0W100</items:value>
			</items:item>

			<items:itemList key="TABLE_TYPE">
				<items:item>
					<items:key>S</items:key>
					<items:value>true</items:value>
				</items:item>
				<items:item>
					<items:key>R</items:key>
					<items:value>false</items:value>
				</items:item>
				<items:item>
					<items:key>T</items:key>
					<items:value>true</items:value>
				</items:item>
				<items:item>
					<items:key>W</items:key>
					<items:value>false</items:value>
				</items:item>
			</items:itemList>
			<items:itemList key="TABLE_SERIOUS">
				<items:item>
					<items:key>SYM_CODE</items:key>
					<items:value>0Z5</items:value>
				</items:item>				
			</items:itemList>
		</items:itemList>
	</items:itemList>
</items:config>
